name: ordering
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  audioplayers: ^6.5.0
  video_player: ^2.10.0
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  intl: ^0.20.2
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/service_account.json
    - assets/sqlite_schema/columns.json
    - assets/images/aiyah.png
    - assets/audio/gulay-gulay_kim.mp3
    - assets/mp4/aiyah.mp4